### ISSUE TITLE
Implement new translation

### ISSUE THREAD

**Issue by AliMehraei** [upjs/facile-validator#227]
Dear Ali,
May I ask you to :
1 - Describe how to add new built-in language?
2 - Why data-rule not working on "textarea" tag.
3 - How to change the language on website/web application dynamically? (laravel 9 project)
thanks

**Comment by AliN11** [comment]
Hello dear @AliMehraei. Thanks for your contact.

1. We provide an easy way to add own languages with the help of `createLang` function which is described [here](https://github.com/upjs/facile-validator#using-your-own-language):
```js
import { Validator, enLang as en, createLang } from '@upjs/facile-validator';

const myLang = createLang({
  required: 'Please fill out this field',
  accepted: 'Please accept this field',
  // All other keys should be defined
});

const v = new Validator(form, {
  lang: myLang,
});
```
However, if you want to add built-in languages, you can fork and add the languages to the package's core. Also any pull request for adding other languages are welcome.

2. This works since version 1.7. Please update the package:
```bash
npm i @upjs/facile-validator

# or
yarn add @upjs/facile-validator
```

3. Since version 1.7 you can change the language at run-time with the help of `setLanguage` method from the validator instance:
```js
import { Validator, enLang as en, faLang as fa } from '@upjs/facile-validator';

const v = new Validator(form, {
  lang: en,
}

// This
v.setLanguage(fa);
```

**Comment by AliMehraei** [comment]
Thank you dear Ali for your reply.
And what about the "textarea" tag?

**Comment by AliN11** [comment]
> Thank you dear Ali for your reply. And what about the "textarea" tag?

You're welcome. I explained in the 2nd segment of my previous answer. Please update the package and use `data-rules` for `textarea` tag like other inputs.

**Comment by AliMehraei** [comment]
Thank you so much @AliN11 .
I'll inform you about the test results.

**Comment by AliMehraei** [comment]
Dear @AliN11 
Would you please to check the pull requests? 
These locale translations will be updated by native translators during days ahead.
